Lab_TDD/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('status.urls','status'), namespace = 'status')),
    path('myprofile/', include(('status.urls','status'), namespace = 'profile'))
]

status/urls.py
from django.conf.urls import url
from django.urls import re_path
from .views import index,add_status, index_2
from . import views

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path('myprofile/', index_2, name='index_2'),
    re_path('add_status/', add_status, name = 'add_status'),
]

status/models.py
from django.db import models
from datetime import datetime, date

# Create your models here.
class Status(models.Model):
	date = models.DateTimeField(default = datetime.now())
	status = models.TextField(max_length = 300)

status/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class Status_Form(forms.ModelForm):
    status = forms.CharField(label='Status', required = True, widget = forms.TextInput())

    class Meta :
        model = Status
        fields = ('status',)

status/views.py
from django.shortcuts import render, redirect
from .models import Status
from datetime import datetime
from .forms import Status_Form
from . import forms
from django.http import HttpResponseRedirect

response = {}
def index(request):
	response['form'] = forms.Status_Form
	response['status'] = Status.objects.all()
	html = 'lab_6.html'
	return render(request, html, response)

def index_2(request):
    return render(request, 'my_profile.html')

def add_status(request):
	form = forms.Status_Form(request.POST)
	if form.is_valid():
		response['status'] = request.POST['status']
		status = Status(status = response['status'])
		status.save()
		return HttpResponseRedirect('/')
	else:
		form = forms.Status_Form()

	return render(request, 'lab_6.html', response)

status/templates/lab_6.html
<!DOCTYPE html>
<html>
<head>
    <title>Graciela Chika Putri</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head>

<body>
    <div class="jumbotron">
        <h1 style="font-size : 50px"> Hello, Apa kabar? </h1>
    </div>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="projects">
        <div class="my-auto">
            <h2 class="mb-5">{{ title }}</h2>
            <div class="col-sm-12 form-row field-desc">
                <div>
                    <form id="form" method="POST" action = "{% url 'status:add_status' %}">
                        {% csrf_token %}
                        {{form}}
                        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                    </form>
                </div>
            </div>
        </div>
    </section>
    <div class="table-responsive">
        {% if Status %}
        <table class = "table table-hover">
            <thead>
                <th> Date </th>
                <th> Status </th>
            </thead>
            {% for data in Status %}
            <tr>
            <td> {{ data.date }} </td>
            <td> {{ data.Status }} </td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        <h2> No Status </h2>
        {% endif %}
    </div>     
</body>
</html>>